// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "github.com/satryarangga/amartha-loan-engine/models"

	repositories "github.com/satryarangga/amartha-loan-engine/repositories"
)

// BorrowerRepository is an autogenerated mock type for the BorrowerRepository type
type BorrowerRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, param
func (_m *BorrowerRepository) FindAll(ctx context.Context, param models.FindAllParam) ([]models.Borrower, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Borrower
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.FindAllParam) ([]models.Borrower, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.FindAllParam) []models.Borrower); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Borrower)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.FindAllParam) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id, relations
func (_m *BorrowerRepository) FindByID(ctx context.Context, id string, relations []string) (*models.Borrower, error) {
	ret := _m.Called(ctx, id, relations)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Borrower
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (*models.Borrower, error)); ok {
		return rf(ctx, id, relations)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) *models.Borrower); ok {
		r0 = rf(ctx, id, relations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrower)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, id, relations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneByPhoneNumber provides a mock function with given fields: ctx, phoneNumber
func (_m *BorrowerRepository) FindOneByPhoneNumber(ctx context.Context, phoneNumber string) (models.Borrower, error) {
	ret := _m.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindOneByPhoneNumber")
	}

	var r0 models.Borrower
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Borrower, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Borrower); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		r0 = ret.Get(0).(models.Borrower)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, tx, model
func (_m *BorrowerRepository) Insert(ctx context.Context, tx *gorm.DB, model *models.Borrower) (string, error) {
	ret := _m.Called(ctx, tx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Borrower) (string, error)); ok {
		return rf(ctx, tx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Borrower) string); ok {
		r0 = rf(ctx, tx, model)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, *models.Borrower) error); ok {
		r1 = rf(ctx, tx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tx, model
func (_m *BorrowerRepository) Update(ctx context.Context, tx *gorm.DB, model *models.Borrower) error {
	ret := _m.Called(ctx, tx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Borrower) error); ok {
		r0 = rf(ctx, tx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *BorrowerRepository) WithTransaction(ctx context.Context, fn repositories.TransactionFunc) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.TransactionFunc) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBorrowerRepository creates a new instance of BorrowerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorrowerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorrowerRepository {
	mock := &BorrowerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
