// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "github.com/satryarangga/amartha-loan-engine/models"

	repositories "github.com/satryarangga/amartha-loan-engine/repositories"
)

// LoanScheduleRepository is an autogenerated mock type for the LoanScheduleRepository type
type LoanScheduleRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, param
func (_m *LoanScheduleRepository) FindAll(ctx context.Context, param models.FindAllParam) ([]models.LoanSchedule, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.LoanSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.FindAllParam) ([]models.LoanSchedule, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.FindAllParam) []models.LoanSchedule); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LoanSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.FindAllParam) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id, relations
func (_m *LoanScheduleRepository) FindByID(ctx context.Context, id string, relations []string) (*models.LoanSchedule, error) {
	ret := _m.Called(ctx, id, relations)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.LoanSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (*models.LoanSchedule, error)); ok {
		return rf(ctx, id, relations)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) *models.LoanSchedule); ok {
		r0 = rf(ctx, id, relations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, id, relations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDueRepaymentSchedules provides a mock function with given fields: ctx, loanID
func (_m *LoanScheduleRepository) FindDueRepaymentSchedules(ctx context.Context, loanID string) ([]models.LoanSchedule, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for FindDueRepaymentSchedules")
	}

	var r0 []models.LoanSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.LoanSchedule, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.LoanSchedule); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LoanSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, tx, model
func (_m *LoanScheduleRepository) Insert(ctx context.Context, tx *gorm.DB, model *models.LoanSchedule) (string, error) {
	ret := _m.Called(ctx, tx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.LoanSchedule) (string, error)); ok {
		return rf(ctx, tx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.LoanSchedule) string); ok {
		r0 = rf(ctx, tx, model)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, *models.LoanSchedule) error); ok {
		r1 = rf(ctx, tx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tx, model
func (_m *LoanScheduleRepository) Update(ctx context.Context, tx *gorm.DB, model *models.LoanSchedule) error {
	ret := _m.Called(ctx, tx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.LoanSchedule) error); ok {
		r0 = rf(ctx, tx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByIDs provides a mock function with given fields: ctx, tx, ids, status
func (_m *LoanScheduleRepository) UpdateStatusByIDs(ctx context.Context, tx *gorm.DB, ids []string, status models.LoanScheduleStatus) error {
	ret := _m.Called(ctx, tx, ids, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []string, models.LoanScheduleStatus) error); ok {
		r0 = rf(ctx, tx, ids, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *LoanScheduleRepository) WithTransaction(ctx context.Context, fn repositories.TransactionFunc) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.TransactionFunc) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLoanScheduleRepository creates a new instance of LoanScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanScheduleRepository {
	mock := &LoanScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
