// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// TransactionFunc is an autogenerated mock type for the TransactionFunc type
type TransactionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: tx
func (_m *TransactionFunc) Execute(tx *gorm.DB) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionFunc creates a new instance of TransactionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionFunc {
	mock := &TransactionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
